controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true  # Habilitar el tiempo simulado

    joint_state_broadcaster:
      use_sim_time: true
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      use_sim_time: true
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      use_sim_time: true
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    use_sim_time: true  # Habilitar el tiempo simulado
    joints:
      - fl_steering_joint
      - fr_steering_joint
      - rl_steering_joint
      - rr_steering_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
